/*
* generated by Xtext
*/
package de.fhb.mdsd.ui.contentassist;

import de.fhb.mdsd.ui.contentassist.AbstractMobileProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MobileProposalProvider extends AbstractMobileProposalProvider {

}
