/*
 * generated by Xtext
 */
package de.fhb.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MobileUiModule extends de.fhb.mdsd.ui.AbstractMobileUiModule {
	public MobileUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
