/*
* generated by Xtext
*/
package de.fhb.mdsd.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MobileOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
