/*
 * generated by Xtext
 */
package de.fhb.mdsd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MobileRuntimeModule extends de.fhb.mdsd.AbstractMobileRuntimeModule {

}
